"""The HDI artifacts generated from the models, and their deployment.

No SAP HANA is needed: the generator only compiles DDL with the HANA dialect,
and the deployment runs against a fake of the two ``hdbcli`` objects it uses
(connection, cursor) that answers HDI's procedures the way a container does:
result sets with a message table whose ``SEVERITY`` column says whether the
call worked. The same deployment against a real container is
``tests/test_hana_integration.py``.

Run:  python -m pytest tests/test_hana_hdi.py -q
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from tests.testdb import use_test_database  # noqa: E402

use_test_database()

from sqlalchemy import (  # noqa: E402
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.schema import CreateTable  # noqa: E402

import agents.ide.models  # noqa: E402,F401  (registers the IDE tables)
from agents import hana_hdi  # noqa: E402
from agents.db import Base  # noqa: E402
from agents.hana_hdi import HdiCredentials, HdiError, artifacts, deploy_files  # noqa: E402
from tests.hana_sql import HANA  # noqa: E402

PASSWORD = "dt-s3cret-value"
CERTIFICATE = "-----BEGIN CERTIFICATE-----\nMIIFAKE\n-----END CERTIFICATE-----"
CREDENTIALS = HdiCredentials(
    host="hana.example.internal", port=443, schema="CONTAINER_1", user="CONTAINER_1_DT",
    password=PASSWORD, certificate=CERTIFICATE,
)
FILES = artifacts(Base.metadata)


def of(suffix: str, files: dict[str, str] = FILES) -> dict[str, str]:
    return {p: c for p, c in files.items() if p.endswith("." + suffix)}


# --- the generator -------------------------------------------------------------------


def test_every_table_index_and_constraint_of_the_models_has_its_artifact():
    tables = Base.metadata.sorted_tables
    assert set(of("hdbtable")) == {f"src/{t.name}.hdbtable" for t in tables}
    indexes = {i.name for t in tables for i in t.indexes}
    uniques = {c.name for t in tables for c in t.constraints
               if isinstance(c, UniqueConstraint)}
    assert not indexes & uniques
    assert set(of("hdbindex")) == {f"src/{n}.hdbindex" for n in indexes | uniques}
    foreign_keys = [fk for t in tables for fk in t.foreign_key_constraints]
    assert len(of("hdbconstraint")) == len(foreign_keys) > 0
    assert len(FILES) == len(tables) + len(indexes | uniques) + len(foreign_keys) + 2


def test_a_table_artifact_is_a_column_table_with_columns_and_key_only():
    for path, content in of("hdbtable").items():
        assert content.startswith("COLUMN TABLE "), path
        for refused in ("CONSTRAINT", "FOREIGN KEY", "UNIQUE", "DATETIME", "CREATE "):
            assert refused not in content, (path, refused)


def test_a_table_artifact_holds_exactly_the_columns_the_dialect_would_create():
    """Checked against the dialect's own ``CREATE TABLE``, column by column."""
    for table in Base.metadata.sorted_tables:
        whole = str(CreateTable(table).compile(dialect=HANA))
        expected = set()
        for line in whole.splitlines()[2:-2]:
            line = line.strip().rstrip(",").strip()
            if line.startswith(("CONSTRAINT ", "FOREIGN KEY", "UNIQUE ")):
                continue
            expected.add(line.replace(" DATETIME", " TIMESTAMP"))
        content = FILES[f"src/{table.name}.hdbtable"]
        got = {line.strip().rstrip(",") for line in content.splitlines()[1:-1]}
        assert got == expected, table.name
        assert len(got) == len(table.columns) + 1  # and the primary key


def test_timestamps_identity_and_lobs_are_written_the_way_hdi_takes_them():
    agent_configs = FILES["src/agent_configs.hdbtable"]
    assert "id INTEGER GENERATED BY DEFAULT AS IDENTITY" in agent_configs
    assert "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL" in agent_configs
    assert "instructions NCLOB NOT NULL" in agent_configs
    assert "PRIMARY KEY (id)" in agent_configs
    assert "non_production BOOLEAN" in FILES["src/ide_conventions.hdbtable"]


def test_a_unique_constraint_and_a_partial_index_are_plain_unique_indexes():
    assert FILES["src/uq_agent_configs_name.hdbindex"] == (
        "UNIQUE INDEX uq_agent_configs_name ON agent_configs (name)\n"
    )
    # Partial (WHERE api_slug IS NOT NULL) on Postgres and SQLite; HANA
    # allows several NULLs in a unique index, so no predicate is needed.
    assert FILES["src/uq_agent_configs_api_slug.hdbindex"] == (
        "UNIQUE INDEX uq_agent_configs_api_slug ON agent_configs (api_slug)\n"
    )
    for path, content in of("hdbindex").items():
        assert re.fullmatch(r"(UNIQUE )?INDEX \w+ ON \w+ \([\w, ]+\)\n", content), path


def test_a_foreign_key_is_a_constraint_artifact_with_its_cascade():
    comments = [c for c in of("hdbconstraint").values() if " ON ide_comments " in c]
    assert comments == [
        "CONSTRAINT fk_ide_comments_session_id ON ide_comments FOREIGN KEY "
        "(session_id) REFERENCES ide_sessions (id) ON DELETE CASCADE\n"
    ]


def test_the_two_configuration_files():
    assert json.loads(FILES["src/.hdiconfig"]) == {"file_suffixes": {
        "hdbtable": {"plugin_name": "com.sap.hana.di.table"},
        "hdbindex": {"plugin_name": "com.sap.hana.di.index"},
        "hdbconstraint": {"plugin_name": "com.sap.hana.di.constraint"},
    }}
    assert json.loads(FILES["src/.hdinamespace"]) == {"name": "", "subfolder": "ignore"}


def test_the_output_is_deterministic_and_ordered():
    again = artifacts(Base.metadata)
    assert list(again.items()) == list(FILES.items())
    paths = list(FILES)
    assert paths[:2] == ["src/.hdiconfig", "src/.hdinamespace"]
    suffixes = [p.rsplit(".", 1)[-1] for p in paths[2:]]
    assert suffixes == sorted(suffixes, key=["hdbtable", "hdbindex", "hdbconstraint"].index)
    assert all(content.endswith("\n") and "\r" not in content for content in FILES.values())


def _small(*extra: Any) -> MetaData:
    metadata = MetaData()
    Table("parents", metadata, Column("id", Integer, primary_key=True))
    Table(
        "children", metadata,
        Column("id", String(36), primary_key=True),
        Column("parent_id", Integer, ForeignKey("parents.id"), nullable=False),
        Column("label", String(20)),
        Column("body", Text),
        Column("seen_at", DateTime(timezone=True)),
        *extra,
    )
    return metadata


def test_an_index_that_leaves_the_models_leaves_the_artifacts():
    with_index = artifacts(_small(Index("ix_children_label", "label")))
    without = artifacts(_small())
    assert set(with_index) - set(without) == {"src/ix_children_label.hdbindex"}
    assert with_index["src/ix_children_label.hdbindex"] == (
        "INDEX ix_children_label ON children (label)\n"
    )
    # An unnamed foreign key gets a stable name; no cascade was asked for.
    assert without["src/fk_children_parent_id.hdbconstraint"] == (
        "CONSTRAINT fk_children_parent_id ON children FOREIGN KEY (parent_id) "
        "REFERENCES parents (id)\n"
    )
    assert "seen_at TIMESTAMP" in without["src/children.hdbtable"]


@pytest.mark.parametrize("extra, reason", [
    (UniqueConstraint("label"), "unique constraint on children has no name"),
    (CheckConstraint("label <> ''", name="ck_label"), "CheckConstraint on children"),
    (UniqueConstraint("label", name="ix_dup"), "share the artifact src/ix_dup.hdbindex"),
])
def test_what_has_no_artifact_fails_the_generator_not_the_deployment(extra, reason):
    more = (Index("ix_dup", "body"),) if "ix_dup" in reason else ()
    with pytest.raises(HdiError, match=reason):
        artifacts(_small(extra, *more))


# --- a fake container ----------------------------------------------------------------

MESSAGE_COLUMNS = ("REQUEST_ID", "ROW_ID", "LEVEL", "TYPE", "LIBRARY_ID", "PLUGIN_ID",
                   "PATH", "SEVERITY", "MESSAGE_CODE", "MESSAGE", "LOCATION",
                   "LOCATION_PATH", "TIMESTAMP_UTC")
LISTING_COLUMNS = ("PATH", "CREATE_USER_NAME", "CREATE_APPUSER_NAME", "CREATE_TIMESTAMP_UTC",
                   "MODIFICATION_USER_NAME", "MODIFICATION_APPUSER_NAME",
                   "MODIFICATION_TIMESTAMP_UTC", "SIZE", "SHA256")
GEN = hana_hdi.HANA_SCHEMA_GENERATION
RECORD = hana_hdi.GENERATION_FILE


def message(severity: str, text: str, path: str | None = None, code: int = 0) -> tuple:
    return (1, 1, 0, "HDI", None, None, path, severity, code, text, None, None, None)


def not_found(path: str) -> list[tuple]:
    """HDI's answer to a LIST of a path that does not exist, with the
    message codes read off a real container."""
    return [
        message("ERROR", f'The file "{path}" could not be found', code=8212757),
        message("ERROR", "Could not read work files", code=8211562),
        message("ERROR", "Some requested files/folders could not be found", code=8212764),
        message("ERROR", 'Reading 1 work files from the container "CONTAINER_1"... failed',
                code=8214188),
    ]


def folder_not_found(path: str, procedure: str = "LIST") -> list[tuple]:
    """HDI's answer to a LIST / LIST_DEPLOYED of a folder that does not
    exist: what a container nobody deployed to says about ``src/``. Message
    codes read off a real, never-used container; the two procedures differ
    in two of the four."""
    kind, read, summary = (
        ("active", 8211563, 8214191) if procedure == "LIST_DEPLOYED"
        else ("work", 8211562, 8214188)
    )
    return [
        message("ERROR", f'The folder "{path}" could not be found', code=8212760),
        message("ERROR", f"Could not read {kind} files", code=read),
        message("ERROR", "Some requested files/folders could not be found", code=8212764),
        message("ERROR", f'Reading 1 {kind} files from the container "CONTAINER_1"... failed',
                code=summary),
    ]


def record(generation: int, files: dict[str, str] = FILES, *, made: bool = True) -> dict:
    return {RECORD: json.dumps({
        "generation": generation, "made": made, "digest": hana_hdi.schema_digest(files)})}


class FakeContainer:
    """An HDI container as the deployment sees it: the deployed files, the
    design-time file system (``work``; it also holds the generation record),
    and procedures that answer with message tables the way the real ones do
    (a DELETE or LIST of a path that is not there is an ERROR row). As
    measured on a real container, every procedure commits its own work: a
    WRITE, a DELETE and a successful MAKE stay whatever the client's
    transaction does afterwards; a refused MAKE changes nothing deployed.
    ``commit`` / ``rollback`` only end the lock. ``calls`` is the order of
    everything."""

    def __init__(self, deployed: dict[str, str] | None = None,
                 generation: int | None = None, *, made: bool = True) -> None:
        self.deployed = dict(deployed or {})
        self.work = dict(self.deployed)
        if generation is not None:
            self.work.update(record(generation, self.deployed, made=made))
        self.replies: dict[str, list[tuple]] = {}
        self.fail_on: dict[str, Exception] = {}
        self.calls: list[str] = []
        self.made: list[tuple[list[str], list[str]]] = []
        self.deleted: list[list[str]] = []
        self.connections: list[FakeConnection] = []

    def connect(self, credentials: HdiCredentials) -> FakeConnection:
        connection = FakeConnection(self)
        self.connections.append(connection)
        return connection

    @property
    def generation(self) -> int | None:
        raw = self.work.get(RECORD)
        return None if raw is None else json.loads(raw)["generation"]

    @property
    def is_made(self) -> bool | None:
        raw = self.work.get(RECORD)
        return None if raw is None else json.loads(raw)["made"]

    def record_matches_schema(self) -> bool:
        return json.loads(self.work[RECORD])["digest"] == hana_hdi.schema_digest(self.deployed)

    def after_setup(self) -> list[str]:
        """The calls of the last deployment, after its temporary tables
        were committed (every deployment starts ``commit``, ``LOCK``)."""
        starts = [i for i, call in enumerate(self.calls[:-1])
                  if call == "commit" and self.calls[i + 1] == "LOCK"]
        return self.calls[starts[-1] + 1:]


class FakeConnection:
    def __init__(self, container: FakeContainer) -> None:
        self.container = container
        self.temp: dict[str, list[tuple]] = {}
        self.closed = 0
        self.locked = False
        self.statements: list[str] = []

    def state(self) -> tuple[dict[str, str], dict[str, str]]:
        return self.container.work, self.container.deployed

    def cursor(self) -> FakeCursor:
        return FakeCursor(self)

    def commit(self) -> None:
        self.container.calls.append("commit")
        self.locked = False

    def rollback(self) -> None:
        self.container.calls.append("rollback")
        self.locked = False

    def close(self) -> None:
        self.closed += 1


class FakeCursor:
    def __init__(self, connection: FakeConnection) -> None:
        self.connection = connection
        self._sets: list[tuple[tuple[str, ...], list[tuple]]] = []
        self.description: Any = None

    # -- the DB-API surface the deployment uses --
    def execute(self, statement: str, parameters: Any = None) -> None:
        connection = self.connection
        container = connection.container
        connection.statements.append(statement)
        created = re.fullmatch(
            r"CREATE LOCAL TEMPORARY COLUMN TABLE (#\w+) LIKE _SYS_DI\.(\w+)", statement)
        if created:
            assert created.group(1) not in connection.temp
            assert not connection.locked, "DDL after the lock would release it"
            connection.temp[created.group(1)] = []
            self._answer([])
            return
        called = re.fullmatch(r'CALL "CONTAINER_1#DI"\.(\w+)\(([^)]*)\)', statement)
        assert called, statement
        procedure, arguments = called.group(1), [a.strip() for a in called.group(2).split(",")]
        container.calls.append(procedure)
        if procedure in container.fail_on:
            raise container.fail_on[procedure]
        work, deployed = connection.state()
        messages = list(container.replies.get(procedure, [message("INFO", "ok")]))
        sets: list[tuple[tuple[str, ...], list[tuple]]] = [(MESSAGE_COLUMNS, messages)]
        failed = any(row[7] == "ERROR" for row in messages)

        def listing(files: dict[str, str], paths: list[tuple]) -> list[tuple]:
            rows = []
            for (path,) in paths:
                if path.endswith("/"):
                    found = {p: c for p, c in files.items() if p.startswith(path)}
                    if not found:
                        # A folder exists only through the files below it.
                        messages.extend(folder_not_found(path, procedure))
                        continue
                    rows.append((path, "U", None, None, "U", None, None, 0, None))
                elif path in files:
                    found = {path: files[path]}
                else:
                    messages.extend(not_found(path))
                    found = {}
                rows += [(p, "U", None, None, "U", None, None, len(c),
                          hashlib.sha256(c.encode()).hexdigest().upper())
                         for p, c in sorted(found.items())]
            return rows

        if procedure == "LOCK":
            assert arguments[0] == str(hana_hdi.LOCK_WAIT_MS)
            connection.locked = True
        elif procedure == "LIST_DEPLOYED":
            sets.append((LISTING_COLUMNS, listing(deployed, connection.temp[arguments[0]])))
        elif procedure == "LIST":
            sets.append((LISTING_COLUMNS, listing(work, connection.temp[arguments[0]])))
        elif procedure == "READ":
            rows = listing(work, connection.temp[arguments[0]])
            sets.append((LISTING_COLUMNS + ("CONTENT",),
                         [row + (work[row[0]].encode(),) for row in rows]))
        elif procedure == "WRITE" and not failed:
            for path, content in connection.temp[arguments[0]]:
                if content is not None:
                    work[path] = content.decode("utf-8")
        elif procedure == "DELETE" and not failed:
            paths = [p for (p,) in connection.temp[arguments[0]]]
            container.deleted.append(paths)
            for path in paths:
                if path not in work:
                    messages.append(message("ERROR", f'The file "{path}" could not be found'))
                else:
                    del work[path]
        elif procedure == "MAKE" and not failed:
            deploy = [p for (p,) in connection.temp[arguments[0]]]
            undeploy = [p for (p,) in connection.temp[arguments[1]]]
            assert connection.temp[arguments[2]] == []
            container.made.append((deploy, undeploy))
            for path in deploy:
                deployed[path] = work[path]
            for path in undeploy:
                assert path not in work, "undeployed while still in the file system"
                del deployed[path]
        self._answer(sets)

    def executemany(self, statement: str, rows: list[tuple]) -> None:
        inserted = re.fullmatch(r"INSERT INTO (#\w+) VALUES \(([?, ]+)\)", statement)
        assert inserted, statement
        assert all(len(row) == inserted.group(2).count("?") for row in rows)
        self.connection.temp[inserted.group(1)].extend(rows)

    def fetchall(self) -> list[tuple]:
        return self._sets[0][1]

    def nextset(self) -> bool:
        self._sets.pop(0)
        self.description = [(c,) for c in self._sets[0][0]] if self._sets else None
        return bool(self._sets)

    def _answer(self, sets: list) -> None:
        self._sets = list(sets)
        self.description = [(c,) for c in self._sets[0][0]] if self._sets else None


def run(container: FakeContainer, files: dict[str, str] = FILES, *, generation: int = GEN,
        allow_drop: bool = False) -> hana_hdi.DeployResult:
    return deploy_files(CREDENTIALS, files, generation=generation, allow_drop=allow_drop,
                        connect=container.connect)


# --- the deployment --------------------------------------------------------------------


def test_an_empty_container_gets_every_artifact_in_one_transaction():
    container = FakeContainer()
    result = run(container)

    assert result.changed and result.undeployed == () and result.newer_generation is None
    assert result.deployed == tuple(FILES)
    # The record is looked for, not found, and written with the files.
    assert container.after_setup() == [
        "LOCK", "LIST", "LIST_DEPLOYED", "LIST", "WRITE", "MAKE", "WRITE", "commit"]
    assert container.connections[0].locked is False
    assert container.made == [(list(FILES), [])]
    assert container.deployed == FILES
    assert (container.generation, container.is_made) == (GEN, True)
    assert container.record_matches_schema()
    assert json.loads(container.work[RECORD])["digest"] == hana_hdi.load_history()[GEN]
    assert container.connections[0].closed == 1


def test_the_lock_wait_fits_inside_a_default_start_timeout():
    """Cloud Foundry kills an app that has not started within 60 s (the
    default): an instance waiting for the lock must give up, or get it and
    finish, well before that. A first full deploy was measured at 3 s."""
    assert 10_000 <= hana_hdi.LOCK_WAIT_MS <= 30_000


def test_the_lock_is_taken_first_and_no_ddl_follows_it():
    """Creating a temporary table is DDL, and DDL commits: after the lock it
    would release the lock and commit half a deployment."""
    container = FakeContainer()
    run(container)
    statements = container.connections[0].statements
    lock = next(i for i, s in enumerate(statements) if ".LOCK(" in s)
    assert all(s.startswith("CREATE LOCAL TEMPORARY") for s in statements[:lock])
    assert len(statements[:lock]) == len(hana_hdi._TEMP_TABLES)
    assert not [s for s in statements[lock:] if s.startswith("CREATE ")]
    assert container.calls[0] == "commit" and container.calls[1] == "LOCK"


def test_a_container_that_already_holds_the_files_is_left_alone():
    """Idempotent, and cheap: four reads under the lock, no write, no make."""
    container = FakeContainer(FILES, generation=GEN)
    for _ in range(2):
        result = run(container)
        assert not result.changed and result.undeployed == ()
        assert result.deployed == tuple(FILES) and result.newer_generation is None
    assert container.after_setup() == [
        "LOCK", "LIST", "READ", "LIST_DEPLOYED", "LIST", "commit"]
    assert container.made == [] and container.generation == GEN


def test_files_a_failed_deploy_left_behind_are_removed_even_when_nothing_is_made():
    leftover = "src/zz_broken.hdbindex"
    container = FakeContainer(FILES, generation=GEN)
    container.work[leftover] = "INDEX nonsense"
    result = run(container)
    assert not result.changed and container.made == []
    assert container.deleted == [[leftover]]
    assert {p for p in container.work if p.startswith("src/")} == set(FILES)


@pytest.mark.parametrize("held, made, app", [
    (None, True, GEN),      # deployed before records existed
    (GEN, False, GEN),      # the make finished, its "made" record did not
    (GEN, True, GEN + 1),   # the next generation changed no file
    (GEN, False, GEN + 1),
])
def test_the_same_files_without_a_current_record_only_get_the_record(held, made, app):
    """Nothing to make; the record is brought to "this generation, made"."""
    container = FakeContainer(FILES, generation=held, made=made)
    result = run(container, generation=app)
    assert not result.changed
    assert "MAKE" not in container.calls and "DELETE" not in container.calls
    assert container.calls[-2:] == ["WRITE", "commit"]
    assert (container.generation, container.is_made) == (app, True)
    assert container.deployed == FILES and container.record_matches_schema()


def test_a_changed_artifact_is_made_again():
    older = dict(FILES)
    older["src/agent_configs.hdbtable"] = "COLUMN TABLE agent_configs (\n\tid INTEGER\n)\n"
    container = FakeContainer(older, generation=GEN)
    result = run(container, generation=GEN + 1)
    assert result.changed and result.undeployed == ()
    assert container.deployed == FILES and container.generation == GEN + 1
    assert "DELETE" not in container.calls


def test_an_artifact_that_is_no_longer_generated_is_undeployed():
    gone = "src/ix_job_runs_removed.hdbindex"
    container = FakeContainer(
        {**FILES, gone: "INDEX ix_job_runs_removed ON job_runs (id)\n"}, generation=GEN)

    result = run(container, generation=GEN + 1)

    assert result.changed and result.undeployed == (gone,)
    # Out of the file system first, then named to the make as "undeploy".
    assert container.after_setup() == [
        "LOCK", "LIST", "READ", "LIST_DEPLOYED", "LIST", "WRITE", "DELETE", "MAKE", "WRITE",
        "commit"]
    assert container.deleted == [[gone]]
    assert container.made == [(list(FILES), [gone])]
    assert container.deployed == FILES and gone not in container.work
    # And the next start finds nothing to do.
    assert not run(container, generation=GEN + 1).changed


def test_delete_acts_on_the_file_system_and_undeploy_on_what_is_deployed():
    """The two can differ. A stale file that is deployed but no longer in the
    file system must not be deleted (HDI answers "could not be found") yet
    must be undeployed; a leftover file that was never deployed is deleted
    and is nothing to undeploy."""
    stale = "src/ix_stale.hdbindex"
    leftover = "src/zz_leftover.hdbindex"
    container = FakeContainer({**FILES, stale: "INDEX ix_stale ON job_runs (id)\n"})
    del container.work[stale]
    container.work[leftover] = "INDEX zz_leftover ON job_runs (id)\n"

    result = run(container)

    assert result.changed and result.undeployed == (stale,)
    assert container.deleted == [[leftover]]
    assert container.made == [(list(FILES), [stale])]
    assert container.deployed == FILES
    assert {p for p in container.work if p.startswith("src/")} == set(FILES)


def test_a_stale_file_missing_from_the_file_system_needs_no_delete_call():
    stale = "src/ix_stale.hdbindex"
    container = FakeContainer({**FILES, stale: "INDEX ix_stale ON job_runs (id)\n"})
    del container.work[stale]
    assert run(container).undeployed == (stale,)
    assert "DELETE" not in container.calls


# --- the two guards against an older app version ------------------------------------------


NEWER = {**FILES, "src/future.hdbtable": "COLUMN TABLE future (\n\tid INTEGER\n)\n",
         "src/ix_future.hdbindex": "INDEX ix_future ON future (id)\n"}
OLDER = {p: c for p, c in FILES.items() if "ide_comments" not in p}


def test_a_container_of_a_newer_generation_is_not_touched_at_all():
    """An older app version (a rollback, an old instance during a rolling
    deploy) generates fewer artifacts. The container's record says a newer
    generation was MADE and what is deployed is that schema: the older
    version writes, makes and undeploys nothing, and reports what it found."""
    container = FakeContainer(NEWER, generation=GEN + 3)
    before = dict(container.work)

    result = run(container)

    assert (result.changed, result.undeployed, result.newer_generation) == (False, (), GEN + 3)
    assert container.after_setup() == ["LOCK", "LIST", "READ", "LIST_DEPLOYED", "rollback"]
    assert container.deployed == NEWER and container.work == before
    # Not even with the switch that allows a table drop.
    assert run(container, allow_drop=True).newer_generation == GEN + 3
    assert container.deployed == NEWER and container.work == before


def _refused_untouched(container: FakeContainer, says: str, **kw) -> None:
    before = (dict(container.deployed), dict(container.work))
    with pytest.raises(HdiError, match=says):
        run(container, **kw)
    assert (container.deployed, container.work) == before
    assert not {"WRITE", "DELETE", "MAKE"} & set(container.after_setup())
    assert container.after_setup()[-1] == "rollback"


def test_a_newer_generation_that_was_never_made_refuses_the_older_version():
    """The make of generation N failed (or is still running elsewhere):
    its record is ahead of the schema. Version N-1 must neither deploy its
    own artifacts over it nor start on a schema nobody finished."""
    container = FakeContainer(OLDER, generation=GEN + 1, made=False)
    _refused_untouched(
        container,
        f"unfinished or changed deployment of schema generation {GEN + 1}; this app "
        f"version is generation {GEN}",
    )
    _refused_untouched(container, "unfinished or changed", allow_drop=True)


def test_a_newer_made_record_over_a_different_schema_refuses_the_older_version():
    """The record says "made", but what is deployed is not what that make
    recorded (files missing or changed since): not a schema to run on."""
    container = FakeContainer(NEWER, generation=GEN + 1)
    del container.deployed["src/ix_future.hdbindex"]
    _refused_untouched(container, "unfinished or changed deployment")
    empty = FakeContainer({}, generation=None)
    empty.work.update(record(GEN + 1, NEWER))
    _refused_untouched(empty, "unfinished or changed deployment")


def test_a_failed_first_make_is_finished_by_the_same_version():
    """Fresh container, the first make fails: the record says "not made".
    The same version starts again and completes it."""
    container = FakeContainer()
    container.replies["MAKE"] = [message("ERROR", "out of memory")]
    with pytest.raises(HdiError, match="HDI MAKE failed"):
        run(container)
    assert (container.generation, container.is_made, container.deployed) == (GEN, False, {})

    del container.replies["MAKE"]
    assert run(container).changed
    assert (container.generation, container.is_made) == (GEN, True)
    assert container.deployed == FILES and container.record_matches_schema()
    assert not run(container).changed


def test_a_failed_make_of_a_newer_version_then_the_older_one_changes_nothing():
    container = FakeContainer(OLDER, generation=GEN)
    container.replies["MAKE"] = [message("ERROR", "refused", "src/ide_comments.hdbtable")]
    with pytest.raises(HdiError, match="HDI MAKE failed"):
        run(container, FILES, generation=GEN + 1)
    assert (container.generation, container.is_made) == (GEN + 1, False)
    assert container.deployed == OLDER
    del container.replies["MAKE"]

    # The older version (its own schema is even still deployed) refuses...
    _refused_untouched(container, "unfinished or changed deployment")
    # ...and the newer one finishes what it started.
    assert run(container, FILES, generation=GEN + 1).changed
    assert (container.generation, container.is_made) == (GEN + 1, True)
    # Now the older version skips and runs.
    assert run(container, OLDER).newer_generation == GEN + 1
    assert container.deployed == FILES


def test_a_made_record_whose_schema_is_missing_is_redeployed_by_its_own_version():
    container = FakeContainer({}, generation=None)
    container.work.update(record(GEN))
    result = run(container)
    assert result.changed and container.deployed == FILES
    assert container.is_made is True and container.record_matches_schema()


@pytest.mark.parametrize("content", [
    "not json", "[]", "{}", '{"generation": "7", "made": true, "digest": "%s"}',
    '{"generation": 0, "made": true, "digest": "%s"}',
    '{"generation": true, "made": true, "digest": "%s"}',
    '{"generation": 1, "made": "yes", "digest": "%s"}',
    '{"generation": 1, "made": true}', '{"generation": 1, "made": true, "digest": "abc"}',
    '{"generation": 1}',
])
def test_a_record_that_is_there_and_unreadable_fails_closed(content):
    """Never "no record": that would let an older version deploy over a
    newer schema and write its lower generation over the record."""
    container = FakeContainer(NEWER)
    container.work[RECORD] = content.replace("%s", "0" * 64)
    _refused_untouched(container, r"schema record \(meta/generation.json\) cannot be read")
    assert container.after_setup() == ["LOCK", "LIST", "READ", "rollback"]


def test_a_listing_that_fails_is_not_an_empty_container():
    """Only HDI's exact file-not-found answer means "no record"."""
    for rows, says in (
        ([message("ERROR", "Internal error: insufficient privilege", code=8250009)],
         "HDI LIST failed: Internal error"),
        (not_found(RECORD) + [message("ERROR", "and something else", code=8250009)],
         "HDI LIST failed"),
        ([message("ERROR", "no code at all")], "HDI LIST failed: no code at all"),
    ):
        container = FakeContainer(NEWER, generation=GEN + 1)
        container.replies["LIST"] = rows
        _refused_untouched(container, says)
        assert container.after_setup() == ["LOCK", "LIST", "rollback"]


def test_a_record_is_never_replaced_by_a_lower_generation():
    """Every path that writes the record, tried from an older version."""
    for container in (
        FakeContainer(FILES, generation=GEN + 1),               # same files
        FakeContainer(NEWER, generation=GEN + 1),               # made, newer
        FakeContainer(NEWER, generation=GEN + 1, made=False),   # not made
        FakeContainer(OLDER, generation=GEN + 1, made=False),
    ):
        try:
            run(container, allow_drop=True)
        except HdiError:
            pass
        assert container.generation == GEN + 1


def test_a_table_is_never_dropped_without_the_switch():
    """Whatever the generations say: the deploy is refused before anything
    is written."""
    extra = {**FILES, "src/zz_probe.hdbtable": "COLUMN TABLE zz_probe (\n\tid INTEGER\n)\n",
             "src/ix_zz_probe.hdbindex": "INDEX ix_zz_probe ON zz_probe (id)\n"}
    container = FakeContainer(extra, generation=GEN)

    with pytest.raises(HdiError) as refused:
        run(container, generation=GEN + 1)

    assert str(refused.value) == (
        "this deployment would drop the table(s) zz_probe with every row. Refused: "
        "set HANA_HDI_ALLOW_DROP=true for one start if that is intended"
    )
    assert container.after_setup() == ["LOCK", "LIST", "READ", "LIST_DEPLOYED", "rollback"]
    assert container.deployed == extra and (container.generation, container.is_made) == (GEN, True)

    result = run(container, generation=GEN + 1, allow_drop=True)
    assert set(result.undeployed) == {"src/zz_probe.hdbtable", "src/ix_zz_probe.hdbindex"}
    assert container.deployed == FILES and container.generation == GEN + 1


def test_a_long_list_of_tables_to_drop_is_cut():
    container = FakeContainer(FILES, generation=GEN)
    config = {p: c for p, c in FILES.items() if p.rsplit(".", 1)[-1].startswith("hdi")}
    with pytest.raises(HdiError, match=r"table\(s\) (\w+, ){4}\w+ and \d+ more with every row"):
        run(container, config)
    assert container.deployed == FILES


def test_indexes_and_constraints_are_undeployed_without_the_switch():
    container = FakeContainer(FILES, generation=GEN)
    fewer = {p: c for p, c in FILES.items()
             if p not in ("src/ix_ide_comments_session_state.hdbindex",
                          "src/fk_ide_comments_session_id.hdbconstraint")}
    assert len(run(container, fewer).undeployed) == 2


@pytest.mark.parametrize("value, allowed", [
    ("true", True), ("True", False), ("TRUE", False), ("1", False), ("yes", False),
    (" true", False), ("", False),
])
def test_the_switch_is_exactly_true(monkeypatch, value, allowed):
    monkeypatch.setenv("HANA_HDI_ALLOW_DROP", value)
    assert hana_hdi.allow_drop_from_environment() is allowed
    monkeypatch.delenv("HANA_HDI_ALLOW_DROP")
    assert hana_hdi.allow_drop_from_environment() is False


# --- failures ---------------------------------------------------------------------------


@pytest.mark.parametrize("procedure", ["LOCK", "READ", "LIST_DEPLOYED", "WRITE", "DELETE", "MAKE"])
def test_an_error_row_is_the_failure_and_the_next_deploy_still_works(procedure):
    """The procedure itself does not raise; its message table says so. One
    attempt: a refused artifact is refused again however often. Nothing
    deployed changed; whatever the file system looks like now, the next
    deploy brings the container to the generated files."""
    stale = "src/old.hdbindex"
    container = FakeContainer({**FILES, stale: "INDEX old ON job_runs (id)\n"}, generation=GEN)
    container.work["src/zz_leftover.hdbindex"] = "INDEX nonsense"
    before = dict(container.deployed)
    container.replies[procedure] = [
        message("INFO", "Starting"),
        message("WARNING", "a warning that is not the failure", "src/a.hdbtable"),
        message("ERROR", "Table definition\n  is   invalid", "src/job_runs.hdbtable"),
        message("ERROR", "Second problem"),
    ]
    with pytest.raises(HdiError) as failed:
        run(container)

    assert str(failed.value) == (
        f"HDI {procedure} failed: src/job_runs.hdbtable: Table definition is invalid; "
        "Second problem"
    )
    assert container.calls.count(procedure) == 1 and container.calls.count("LOCK") == 1
    assert container.after_setup()[-2:] == [procedure, "rollback"]
    assert container.deployed == before
    (connection,) = container.connections
    assert connection.closed == 1 and connection.locked is False

    del container.replies[procedure]
    result = run(container)
    assert result.changed and result.undeployed == (stale,)
    assert container.deployed == FILES
    assert {p for p in container.work if p.startswith("src/")} == set(FILES)


def test_a_failed_make_after_a_delete_leaves_a_container_the_next_deploy_can_use():
    """HDI has committed the DELETE of the stale file when the make fails,
    and no rollback brings it back: the file is gone from the file system
    and still deployed. The next deploy must not try to delete it again
    (HDI answers "could not be found", and every later start failed on
    that) and must still undeploy it."""
    stale = "src/old.hdbindex"
    container = FakeContainer({**FILES, stale: "INDEX old ON job_runs (id)\n"}, generation=GEN)
    broken = {**FILES, "src/zz_broken.hdbindex": "INDEX nonsense"}
    container.replies["MAKE"] = [message("ERROR", "syntax error", "src/zz_broken.hdbindex")]
    with pytest.raises(HdiError, match="HDI MAKE failed: src/zz_broken.hdbindex"):
        run(container, broken, generation=GEN + 1)
    assert "DELETE" in container.calls
    assert stale not in container.work and stale in container.deployed
    assert "src/zz_broken.hdbindex" in container.work
    # Recorded before the make, as "not made": no older app version deploys
    # to it or runs on it from now on.
    assert (container.generation, container.is_made) == (GEN + 1, False)

    del container.replies["MAKE"]
    result = run(container, generation=GEN + 1)
    assert result.changed and result.undeployed == (stale,)
    assert container.deleted[-1] == ["src/zz_broken.hdbindex"]
    assert container.deployed == FILES
    assert (container.generation, container.is_made) == (GEN + 1, True)
    assert {p for p in container.work if p.startswith("src/")} == set(FILES)


def test_warnings_alone_are_not_a_failure():
    container = FakeContainer()
    container.replies["MAKE"] = [message("WARNING", "deprecated syntax", "src/x.hdbtable")]
    assert run(container).changed
    assert container.calls[-1] == "commit"


def test_a_long_list_of_errors_is_cut_and_counted():
    container = FakeContainer()
    container.replies["MAKE"] = [message("ERROR", f"problem {n} " + "x" * 900)
                                 for n in range(25)]
    with pytest.raises(HdiError) as failed:
        run(container)
    text = str(failed.value)
    assert text.count("problem ") == 20 and text.endswith("; and 5 more")
    assert len(text) < 20 * 520 + 100


def test_a_message_that_echoes_a_credential_is_scrubbed():
    container = FakeContainer()
    container.replies["WRITE"] = [message(
        "ERROR", f'bad login {PASSWORD} / {CERTIFICATE} in container "CONTAINER_1"')]
    with pytest.raises(HdiError) as failed:
        run(container)
    assert PASSWORD not in str(failed.value) and "MIIFAKE" not in str(failed.value)
    assert "bad login ***" in str(failed.value)
    # Nor the container's schema name, which HDI's own messages do carry.
    assert str(failed.value).endswith('in container "<container>"')


class DriverError(Exception):
    """Like ``hdbcli.dbapi.Error``: a code and a text that names the host."""

    def __init__(self, errorcode: int, text: str) -> None:
        super().__init__(errorcode, text)
        self.errorcode = errorcode


LEAKY = f"connect failed {{hana.example.internal:443}} user CONTAINER_1_DT pwd {PASSWORD}"


def _no_leak(error: BaseException) -> None:
    shown = str(error) + repr(error)
    for secret in (PASSWORD, "MIIFAKE", "hana.example.internal", "CONTAINER_1_DT"):
        assert secret not in shown
    # Not chained either: a logged traceback would print the driver's text.
    assert error.__cause__ is None and error.__suppress_context__


def test_a_failed_connection_names_the_error_code_never_the_driver_text():
    attempts: list[int] = []

    def refuse(credentials):
        attempts.append(1)
        raise DriverError(10, LEAKY)

    with pytest.raises(HdiError) as failed:
        deploy_files(CREDENTIALS, FILES, generation=GEN, connect=refuse)
    assert str(failed.value) == (
        "could not connect to the HDI container as its design-time user "
        "(DriverError, code 10)"
    )
    assert attempts == [1]
    _no_leak(failed.value)


def test_a_driver_error_during_the_calls_is_rolled_back_and_not_repeated():
    container = FakeContainer()
    container.fail_on["MAKE"] = DriverError(258, LEAKY)
    with pytest.raises(HdiError) as failed:
        run(container)
    assert str(failed.value) == "the HDI deployment failed (DriverError, code 258)"
    _no_leak(failed.value)
    assert container.calls[-1] == "rollback" and container.calls.count("MAKE") == 1
    assert container.deployed == {} and container.connections[0].closed == 1


def test_a_container_lock_that_is_never_released_is_a_clear_failure():
    """Another deployment holds the container for longer than the wait: the
    driver reports a lock timeout, which is named as what it is."""
    container = FakeContainer(FILES, generation=GEN)
    container.fail_on["LOCK"] = DriverError(131, LEAKY)
    with pytest.raises(HdiError) as failed:
        run(container)
    assert str(failed.value) == (
        "another deployment held the HDI container lock for more than 30 s")
    _no_leak(failed.value)
    assert container.after_setup() == ["LOCK", "rollback"]


@pytest.mark.parametrize("schema", ['C1"; DROP', "", "a b", "C1#DI", "x" * 121])
def test_a_schema_name_that_is_not_an_identifier_never_reaches_a_statement(schema):
    container = FakeContainer()
    credentials = HdiCredentials("h", 443, schema, "u", PASSWORD)
    with pytest.raises(HdiError, match="not a plain identifier"):
        deploy_files(credentials, FILES, generation=GEN, connect=container.connect)
    assert container.connections == []


@pytest.mark.parametrize("path", ["other/x.hdbtable", "src/", "x.hdbtable", "meta/generation.json"])
def test_only_files_below_the_artifact_folder_are_written(path):
    container = FakeContainer()
    with pytest.raises(HdiError, match="below src/"):
        run(container, {path: "x"})
    assert container.connections == []


@pytest.mark.parametrize("generation", [0, -1, True, "1", 1.0, None])
def test_a_generation_is_a_positive_integer(generation):
    container = FakeContainer()
    with pytest.raises(HdiError, match="positive integer"):
        run(container, generation=generation)
    assert container.connections == []


# --- the pinned history ---------------------------------------------------------------------

BUMP = (
    "The models (or the generator) changed an HDI artifact. Raise "
    "HANA_SCHEMA_GENERATION in agents/hana_hdi.py by one, run "
    "`.venv/bin/python scripts/hana_schema_history.py` and commit both files: "
    "a container only accepts a schema change from a higher generation."
)


def test_the_current_generation_pins_exactly_the_generated_artifacts():
    history = hana_hdi.load_history()
    assert history.get(GEN) == hana_hdi.schema_digest(FILES), BUMP


def test_generations_count_up_from_one_without_a_gap():
    history = hana_hdi.load_history()
    assert sorted(history) == list(range(1, GEN + 1)), BUMP
    assert all(re.fullmatch(r"[0-9a-f]{64}", digest) for digest in history.values())
    # Two generations never pin the same artifacts: nothing would have changed.
    assert len(set(history.values())) == len(history)


def test_the_digest_covers_paths_and_contents():
    base = hana_hdi.schema_digest({"src/a": "1", "src/b": "2"})
    assert base == hana_hdi.schema_digest({"src/b": "2", "src/a": "1"})
    assert base != hana_hdi.schema_digest({"src/a": "1", "src/b": "3"})
    assert base != hana_hdi.schema_digest({"src/a": "1", "src/c": "2"})
    assert base != hana_hdi.schema_digest({"src/a": "1\0src/b", "": "2"})


def test_a_new_not_null_column_needs_a_server_default():
    """On HANA the models are the only DDL: HDI adds a new column to a table
    that already has rows, and NOT NULL without a default cannot be filled.
    The columns that exist today are pinned; a new one must carry a
    ``server_default`` (or be nullable)."""
    pinned = set(json.loads(
        (ROOT / "tests" / "fixtures" / "hana" / "not_null_without_default.json").read_text()))
    today = {
        f"{table.name}.{column.name}"
        for table in Base.metadata.sorted_tables for column in table.columns
        if not column.nullable and not column.primary_key and column.server_default is None
    }
    assert today - pinned == set(), (
        "NOT NULL without server_default: give the column a server_default (HDI must "
        "add it to tables that hold rows); do not add it to the pinned list"
    )
    assert pinned - today == set(), "remove columns that are gone from the pinned list"


# --- credentials ------------------------------------------------------------------------


def test_credentials_never_show_a_value():
    shown = repr(CREDENTIALS) + str(CREDENTIALS) + f"{CREDENTIALS}"
    for value in (PASSWORD, "MIIFAKE", "CONTAINER_1_DT", "hana.example.internal"):
        assert value not in shown


def test_credentials_come_from_the_design_time_fields_of_a_binding():
    binding = {"host": "h", "port": "443", "schema": "C1", "user": "C1_RT",
               "password": "runtime", "hdi_user": "C1_DT", "hdi_password": PASSWORD,
               "certificate": CERTIFICATE}
    assert hana_hdi.credentials_from_binding(binding) == HdiCredentials(
        "h", 443, "C1", "C1_DT", PASSWORD, CERTIFICATE)
    del binding["hdi_user"], binding["hdi_password"]
    with pytest.raises(HdiError) as refused:
        hana_hdi.credentials_from_binding(binding)
    assert "hdi_user, hdi_password" in str(refused.value)
    assert "hdi-shared" in str(refused.value) and "runtime" not in str(refused.value)


class _Driver:
    """``hdbcli.dbapi.connect``: what it was given, and a connection that
    starts, as the real one does, with autocommit ON."""

    def __init__(self) -> None:
        self.kwargs: dict[str, Any] = {}
        self.autocommit = True

    def connect(self, **kwargs: Any) -> _Driver:
        self.kwargs = kwargs
        return self

    def setautocommit(self, value: bool) -> None:
        self.autocommit = value


def test_the_real_connection_is_encrypted_validated_and_one_transaction(monkeypatch):
    import hdbcli.dbapi

    driver = _Driver()
    monkeypatch.setattr(hdbcli.dbapi, "connect", driver.connect)
    connection = hana_hdi._connect(CREDENTIALS)
    assert driver.kwargs == {
        "address": "hana.example.internal", "port": 443, "user": "CONTAINER_1_DT",
        "password": PASSWORD, "encrypt": True, "sslValidateCertificate": True,
        "sslTrustStore": CERTIFICATE,
    }
    # hdbcli's default is autocommit: every HDI call would commit alone.
    assert connection is driver and driver.autocommit is False

    driver = _Driver()
    monkeypatch.setattr(hdbcli.dbapi, "connect", driver.connect)
    hana_hdi._connect(HdiCredentials("h", 443, "C1", "u", PASSWORD))
    assert driver.kwargs["encrypt"] is True and driver.kwargs["sslValidateCertificate"] is True
    assert "sslTrustStore" not in driver.kwargs and driver.autocommit is False


# --- deploy(): the models, in a thread, and what it logs ----------------------------------


@pytest.fixture
def deploying(monkeypatch):
    """``deploy`` against a fake container (it has no ``connect`` argument)."""

    def into(container: FakeContainer) -> None:
        monkeypatch.setattr(hana_hdi, "_connect", container.connect)
        real = hana_hdi.deploy_files
        monkeypatch.setattr(
            hana_hdi, "deploy_files",
            lambda credentials, files, **kw: real(
                credentials, files, connect=container.connect, **kw),
        )

    return into


async def test_deploy_generates_from_the_models_and_logs_no_secret(deploying, caplog):
    gone = "src/ix_removed.hdbindex"
    container = FakeContainer({**FILES, gone: "INDEX ix_removed ON job_runs (id)\n"})
    deploying(container)
    with caplog.at_level(logging.DEBUG):
        first = await hana_hdi.deploy(CREDENTIALS, Base.metadata)
        second = await hana_hdi.deploy(CREDENTIALS, Base.metadata)

    assert first.changed and first.undeployed == (gone,) and not second.changed
    assert container.deployed == FILES and container.generation == GEN
    warnings = [r.getMessage() for r in caplog.records if r.levelno == logging.WARNING]
    assert warnings == [f"HDI: undeployed {gone} (no longer part of the models)"]
    for value in (PASSWORD, "MIIFAKE", "hana.example.internal", "CONTAINER_1"):
        assert value not in caplog.text


async def test_deploy_on_a_newer_container_warns_once_with_both_generations(
    deploying, caplog, monkeypatch
):
    newer = {**FILES, "src/future.hdbtable": "COLUMN TABLE future (\n\tid INTEGER\n)\n"}
    container = FakeContainer(newer, generation=GEN + 2)
    deploying(container)
    monkeypatch.setenv("HANA_HDI_ALLOW_DROP", "true")
    with caplog.at_level(logging.INFO, logger="agents.hana_hdi"):
        result = await hana_hdi.deploy(CREDENTIALS, Base.metadata)
    assert result.newer_generation == GEN + 2 and not result.changed
    assert container.deployed == newer
    assert [(r.levelname, r.getMessage()) for r in caplog.records] == [(
        "WARNING",
        f"HDI: the container holds schema generation {GEN + 2}, this app version is "
        f"generation {GEN}. Nothing was deployed; the app runs on the newer schema",
    )]


async def test_deploy_reads_the_drop_switch_from_the_environment(deploying, monkeypatch):
    extra = {**FILES, "src/zz_probe.hdbtable": "COLUMN TABLE zz_probe (\n\tid INTEGER\n)\n"}
    container = FakeContainer(extra)
    deploying(container)
    monkeypatch.delenv("HANA_HDI_ALLOW_DROP", raising=False)
    with pytest.raises(HdiError, match="would drop the table"):
        await hana_hdi.deploy(CREDENTIALS, Base.metadata)
    assert container.deployed == extra
    monkeypatch.setenv("HANA_HDI_ALLOW_DROP", "true")
    assert (await hana_hdi.deploy(CREDENTIALS, Base.metadata)).undeployed == (
        "src/zz_probe.hdbtable",)


# -- a container nobody ever deployed to --------------------------------------
def test_a_never_used_container_has_no_folders_and_is_read_as_empty():
    """The first start on a new container: ``src/`` exists in neither file
    system, so both listings answer "folder not found". That is an empty
    container, not a failure."""
    container = FakeContainer()
    result = run(container)
    assert result.changed is True
    assert set(container.deployed) == set(FILES)


@pytest.mark.parametrize("procedure", ["LIST_DEPLOYED", "LIST"])
def test_a_folder_listing_that_fails_otherwise_is_not_an_empty_container(procedure):
    """Only HDI's folder-not-found answer means "nothing there": the same
    answer with one more error in it is a failure, and nothing is written."""
    container = FakeContainer()
    container.replies[procedure] = [message("ERROR", "something else", code=8250009)]
    with pytest.raises(hana_hdi.HdiError):
        run(container)
    assert "WRITE" not in container.calls and "MAKE" not in container.calls
