import IdeService, { IdeError } from "com/agent/ide/service/IdeService";
import { createBody, formOf, updateBody } from "com/agent/ide/model/conventionsForm";
import { quoteOf } from "com/agent/ide/model/comments";
import FakeBackend from "../integration/FakeBackend";
import { assertSupported, validate, type SchemaDoc } from "./contract/validate";
import {
    checkExchange, FRAME_MODELS, routeDiff, SSE_EVENTS, type ContractDoc, type Exchange, type Verdict
} from "./contract/exchange";

/**
 * The contract between the app, the FakeBackend and the backend.
 *
 * `test/contract/ide-api.schema.json` is backend-owned (regenerated by
 * `scripts/export_ide_schema.py`; never edited here). Its `x-routes` map
 * names each route's request and response model; nothing about routes is
 * hand-written in this file. The scenario drives the REAL `IdeService`
 * against the fake, and an observer around `window.fetch` records every
 * call as it went over the wire, so the request bodies validated are the
 * ones the app sends and the answers validated are the ones the app reads.
 *
 * Coverage does not hang on the scenario: the fake's own route table
 * (`FakeBackend.ROUTES`, which its dispatcher enforces) must equal
 * `x-routes` minus EXCLUDED, and every route of that table must have been
 * answered with a 2xx and checked. A drift in the fake is fixed in the fake;
 * an app body the backend would reject, or a schema that looks wrong, is
 * reported, never papered over.
 */

/**
 * `x-routes` entries the fake does not serve because the UI never calls them
 * (no IdeService method; checked by grep of `webapp/` outside `test/`). The
 * test fails when one of them becomes served or leaves `x-routes`.
 */
const EXCLUDED: readonly string[] = [
    // Admin seed refresh: an operator API (runbook curl through the approuter), no UI button.
    "POST /admin/seed/refresh",
    // Object search and open: objects enter a session through the agent or a finding, the UI has no search.
    "GET /objects/search",
    "POST /sessions/{sid}/open"
];

let schema: ContractDoc;
let exchanges: Exchange[] = [];
let verdicts: { ex: Exchange; verdict: Verdict }[] = [];
/** Why the scenario stopped early, if it did; the calls made until then are judged anyway. */
let scenarioError: string | undefined;

const FILE = "src/CLAS/zcl_demo.clas.abap";
const POOL = "ZCL_ORDER_QUERY===============CP";

async function loadSchema(): Promise<ContractDoc> {
    const url = sap.ui.require.toUrl("com/agent/ide/test/contract/ide-api.schema.json");
    return await (await fetch(url)).json() as ContractDoc;
}

/**
 * Installs `fake` and an observer over it that records every `backend/`
 * call; runs `body`; restores both and answers what was recorded.
 */
async function observed(fake: FakeBackend, body: (recorded: readonly Exchange[]) => Promise<void>): Promise<Exchange[]> {
    const recorded: Exchange[] = [];
    fake.install();
    const inner = window.fetch;
    window.fetch = (async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
        const url = String(input);
        if (!url.startsWith("backend/")) {
            return inner(input, init);
        }
        const response = await inner(input, init);
        const method = (init?.method || "GET").toUpperCase();
        const path = url.replace(/^backend\//, "").split("?")[0].replace(/\/$/, "");
        const text = await response.clone().text();
        const route = FakeBackend.routeOf(method, path);
        recorded.push({
            method, path, route: route && route in schema["x-routes"] ? route : undefined,
            requestBody: typeof init?.body === "string" ? init.body : undefined,
            status: response.status, contentType: response.headers.get("Content-Type") ?? "", text
        });
        return response;
    }) as typeof fetch;
    try {
        await body(recorded);
    } finally {
        window.fetch = inner;
        fake.restore();
    }
    return recorded;
}

/** A refusal is part of the scenario: it is validated as ErrorOut, not thrown. */
async function refused(call: Promise<unknown>): Promise<void> {
    try {
        await call;
    } catch (e) {
        if (!(e instanceof IdeError)) {
            throw e;
        }
        return;
    }
    throw new Error("expected a refusal");
}

const ignore = (): void => undefined;

/** Every route of the fake, through the app's own service, with data that makes each answer carry its optional parts. */
async function scenario(fake: FakeBackend, svc: IdeService): Promise<void> {
    await svc.getMe();
    await svc.listSessions();
    await svc.createSession("New change", "dev-system");
    await svc.listConventions();
    // The conventions bodies as the dialog builds them (model/conventionsForm), and the flag's own request.
    await svc.createConventions(createBody(" qa-system ", { ...formOf(undefined), package: " ZQA ", label: "QA", clean_core_level: "B" }));
    const row = await svc.getConventions("dev-system");
    const base = formOf(row);
    const change = updateBody(base, { ...base, package: "", namespace: "/ZNS/", free_text: "Use ABAP Cloud." });
    await svc.putConventions("dev-system", change.body, change.clear); // clears package
    await svc.putConventions("dev-system", { non_production: true });
    await svc.listAllSessions();

    // A change session: a run with activity, files, a document, comments, approve, request changes.
    const sid = fake.sessions[0].session.id;
    fake.withActivity = true;
    await svc.streamMessage(sid, "Explain it", ignore);
    const messages = await svc.listMessages(sid);
    const withActivity = messages.find((m) => m.has_activity);
    await svc.getActivity(sid, withActivity?.id ?? "none");
    fake.addRevision(sid, FILE, "CLASS zcl_demo DEFINITION PUBLIC.\n  \" changed\nENDCLASS.");
    await svc.listFiles(sid);
    await svc.getFile(sid, FILE);
    await svc.getFile(sid, FILE, 1);
    await svc.refreshFile(sid, FILE);
    await svc.lintFile(sid, FILE);
    await svc.listRevisions(sid, FILE);
    await svc.checkSyntax(sid, FILE);
    await svc.checkSyntax(sid, FILE, 1);
    const design = fake.addArtifact(sid, "design");
    await svc.listArtifacts(sid);
    await svc.listArtifacts(sid, "design");
    await svc.getArtifact(sid, design.id);
    await svc.getSession(sid);
    const onFile = await svc.createComment(sid, {
        anchor: "file", path: FILE, revision: 1, line_start: 1, line_end: 2, body: "Why this?", quote: quoteOf("CLASS zcl_demo DEFINITION PUBLIC.")
    });
    const onDoc = await svc.createComment(sid, { anchor: "document", kind: "design", version: 1, paragraph: 0, body: "And this?" });
    await svc.listComments(sid);
    await svc.listComments(sid, "open");
    await svc.editComment(sid, onFile.id, "Why this line?");
    await svc.deleteComment(sid, onFile.id);
    await svc.renameSession(sid, "Renamed");
    // A coded refusal (open comments) is an ErrorOut.
    await refused(svc.approve(sid));
    await svc.setCommentState(sid, onDoc.id, "dismissed");
    await svc.setCommentState(sid, onDoc.id, "open");
    await svc.setCommentState(sid, onDoc.id, "dismissed");
    await svc.approve(sid); // chat -> design, no body
    await svc.approve(sid, 1); // design -> plan, pins version 1
    await refused(svc.streamRequestChanges(sid, undefined, ignore)); // nothing_to_send, body {}
    await svc.streamRequestChanges(sid, "Shorter, please.", ignore);
    await svc.cancel(sid);

    // A diagnose session: findings and a trace request from a run, report, handover.
    fake.allowDiagnose();
    const diagnose = await svc.createSession("Slow orders", "dev-system", "diagnose");
    fake.scriptRun({
        findings: [
            { kind: "dump", ref_id: "D1", title: "TSV_TNEW_PAGE_ALLOC_FAILED", program: POOL, include: POOL, line: 12, occurred_at: "2026-10-03T09:00:00" },
            { kind: "odata_call", ref_id: "O1", title: "GET /sap/opu/odata/X" }
        ],
        approval: {},
        proposalRefused: "trace_limit"
    });
    await svc.streamMessage(diagnose.id, "Why is it slow?", ignore);
    const findings = await svc.listFindings(diagnose.id);
    const dump = findings.find((f) => f.kind === "dump")!;
    await svc.getFinding(diagnose.id, dump.id);
    await svc.getFinding(diagnose.id, dump.id, true);
    await svc.openFinding(diagnose.id, dump.id);
    const approvals = await svc.listApprovals(diagnose.id);
    await svc.decideApproval(diagnose.id, approvals[0].id, "approve");
    // The other decided shapes: arming failed (outcome unknown), approved without a result, denied; an error frame.
    for (const variant of ["failed", "noResult", "deny"] as const) {
        fake.scriptRun({ approval: {} });
        fake.errorFrame = variant === "failed" ? { message: "The model failed.", code: "model_error" } : undefined;
        await svc.streamMessage(diagnose.id, `Trace it (${variant})`, ignore);
        fake.failArming = variant === "failed" ? "arc1_timeout_unknown" : undefined;
        fake.armingWithoutResult = variant === "noResult";
        const pending = (await svc.listApprovals(diagnose.id)).find((a) => a.status === "pending")!;
        await svc.decideApproval(diagnose.id, pending.id, variant === "deny" ? "deny" : "approve");
    }
    fake.failArming = undefined;
    fake.armingWithoutResult = false;
    fake.errorFrame = undefined;
    await svc.listApprovals(diagnose.id);
    await refused(svc.approve(diagnose.id)); // approve_not_allowed
    await svc.streamReport(diagnose.id, ignore);
    const handed = await svc.handover(diagnose.id);
    await svc.getSession(handed.id);
    await svc.deleteSession(handed.id);
}

function judge(list: Exchange[]): { ex: Exchange; verdict: Verdict }[] {
    return list.map((ex) => ({ ex, verdict: checkExchange(schema, ex) }));
}

QUnit.module("Contract: the app and the FakeBackend against the API schema", {
    before: async function () {
        schema = await loadSchema();
        const fake = new FakeBackend();
        fake.reset();
        fake.isAdmin = true;
        const svc = new IdeService();
        exchanges = await observed(fake, async () => {
            try {
                await scenario(fake, svc);
            } catch (e) {
                scenarioError = e instanceof IdeError ? `${e.status} ${e.code ?? ""} ${e.detail}` : String(e);
            }
        });
        verdicts = judge(exchanges);
    }
});

QUnit.test("the scenario ran to its end", function (assert) {
    assert.strictEqual(scenarioError, undefined, "no call of the scenario failed unexpectedly");
});

QUnit.test("the validator judges every keyword the schema uses", function (assert) {
    assertSupported(schema);
    assert.ok(Object.keys(schema.$defs).length > 30, `${Object.keys(schema.$defs).length} models walked`);
});

QUnit.test("every request the app sent and every answer the fake gave conforms to x-routes", function (assert) {
    assert.ok(verdicts.length > 50, `${verdicts.length} calls checked`);
    for (const { ex, verdict } of verdicts) {
        const what = `${ex.method} ${ex.path} (${ex.status}) as ${verdict.model || "nothing"}`
            + (verdict.requestModel ? `, body as ${verdict.requestModel}` : "");
        assert.deepEqual(verdict.errors, [], what);
    }
});

QUnit.test("the fake serves exactly x-routes (minus the commented exclusions)", function (assert) {
    const diff = routeDiff(FakeBackend.ROUTES, Object.keys(schema["x-routes"]), EXCLUDED);
    assert.deepEqual(diff.notInXRoutes, [], "fake routes the backend does not have");
    assert.deepEqual(diff.notServed, [], "x-routes entries the fake does not serve and EXCLUDED does not explain");
    assert.deepEqual(diff.staleExclusions, [], "exclusions that are served or no longer in x-routes");
});

QUnit.test("every route of the fake was answered with a 2xx and checked", function (assert) {
    for (const route of FakeBackend.ROUTES) {
        const hit = verdicts.some(({ ex }) => ex.route === route && ex.status >= 200 && ex.status < 300);
        assert.ok(hit, route);
    }
    assert.ok(verdicts.some(({ verdict }) => verdict.model === "ErrorOut"), "a coded refusal was checked as ErrorOut");
});

QUnit.test("every request model of a served route validated a body the app sent", function (assert) {
    for (const [route, spec] of Object.entries(schema["x-routes"])) {
        if (spec.request && FakeBackend.ROUTES.includes(route)) {
            const hit = verdicts.some(({ ex, verdict }) => ex.route === route && verdict.requestModel === spec.request);
            assert.ok(hit, `${route} body as ${spec.request}`);
        }
    }
    assert.ok(verdicts.some(({ ex }) => ex.route === "PUT /conventions/{target}" && /"clear":\["package"\]/.test(ex.requestBody ?? "")),
        "a conventions update with a clear list was validated");
});

QUnit.test("every SSE event with a model was seen and validated; none was unknown", function (assert) {
    const seen = new Set(verdicts.flatMap(({ verdict }) => verdict.events));
    for (const event of Object.keys(FRAME_MODELS)) {
        assert.ok(seen.has(event), `a ${event} frame was checked as ${FRAME_MODELS[event].model}`);
    }
    for (const event of seen) {
        assert.ok(SSE_EVENTS.includes(event), `${event} is a known event`);
    }
});

QUnit.module("Contract: the test has teeth", {
    before: async function () {
        schema = schema ?? await loadSchema();
    }
});

/** Runs `body` against a fresh fake with a change and a diagnose session; answers the judged calls. */
async function probe(body: (fake: FakeBackend, svc: IdeService, sid: string) => Promise<void>): Promise<{ ex: Exchange; verdict: Verdict }[]> {
    const fake = new FakeBackend();
    fake.reset();
    const svc = new IdeService();
    let setup = 0;
    const list = await observed(fake, async (recorded) => {
        const session = await svc.createSession("Probe", "dev-system");
        setup = recorded.length;
        await body(fake, svc, session.id);
    });
    return judge(list.slice(setup));
}

QUnit.test("a fake answer without a required field fails, with its path", async function (assert) {
    const [call] = await probe(async (fake, svc) => {
        fake.failNext = { path: "me", status: 200, body: { is_admin: false, targets: [], diagnose_targets: [], diagnose_retention_days: 14 } };
        await svc.getMe();
    });
    assert.deepEqual(call.verdict.errors, ["$.principal: required, missing"]);
});

QUnit.test("an unknown field where additionalProperties is false fails", async function (assert) {
    const [call] = await probe(async (_fake, _svc, sid) => {
        await fetch(`backend/sessions/${sid}`, { method: "PATCH", body: JSON.stringify({ title: "x", colour: "red" }) });
    });
    assert.deepEqual(call.verdict.errors, ["request $.colour: not allowed"]);
});

QUnit.test("a wrong request body fails", async function (assert) {
    const calls = await probe(async (_fake, _svc, sid) => {
        await fetch(`backend/sessions/${sid}/messages`, { method: "POST", body: JSON.stringify({ message: "hi" }) });
        await fetch(`backend/sessions/${sid}/approve`, { method: "POST", body: JSON.stringify({ version: "1" }) });
        await fetch(`backend/sessions/${sid}/report`, { method: "POST", body: JSON.stringify({ text: "x" }) });
    });
    assert.ok(calls[0].verdict.errors.includes("request $.text: required, missing"), calls[0].verdict.errors.join("; "));
    assert.ok(calls[0].verdict.errors.includes("request $.message: not allowed"), "and the unknown field");
    assert.ok(calls[1].verdict.errors.some((e) => e.startsWith("request $.version: matches no anyOf branch")),
        calls[1].verdict.errors.join("; "));
    assert.ok(calls[2].verdict.errors.includes("request: a body where the route takes none"), calls[2].verdict.errors.join("; "));
});

QUnit.test("a call the fake does not serve fails", async function (assert) {
    const [call] = await probe(async () => {
        await fetch("backend/objects/search?q=Z", { method: "GET" });
    });
    assert.equal(call.ex.status, 404, "the dispatcher answers only its route table");
    assert.deepEqual(call.verdict.errors, ["GET objects/search: no x-routes entry (no fake route)"]);
});

QUnit.test("an unknown SSE event and a broken frame fail", function (assert) {
    const verdict = checkExchange(schema, {
        method: "POST", path: "sessions/s-1/messages", route: "POST /sessions/{sid}/messages", requestBody: JSON.stringify({ text: "x" }),
        status: 200, contentType: "text/event-stream",
        text: "event: run\ndata: {}\n\nevent: thinking\ndata: {}\n\nevent: tool\ndata: {\"status\":\"ok\"}\n\n"
    });
    assert.deepEqual(verdict.errors, ["unknown event \"thinking\"", "tool frame $.kind: required, missing"]);
});

QUnit.test("route drift either way is listed, and so is a stale exclusion", function (assert) {
    assert.deepEqual(routeDiff(["GET /me", "GET /extra"], ["GET /me", "GET /new", "POST /x"], ["POST /x", "GET /gone"]), {
        notInXRoutes: ["GET /extra"], notServed: ["GET /new"], staleExclusions: ["GET /gone"]
    });
});

QUnit.module("Contract: the validator", {
    before: async function () {
        schema = schema ?? await loadSchema();
    }
});

QUnit.test("a broken response is reported with its path", function (assert) {
    const doc = schema;
    assert.deepEqual(validate(doc, "MeOut", { principal: "p", is_admin: false, targets: [], diagnose_targets: [] }),
        ["$.diagnose_retention_days: required, missing"], "a missing required field");
    const errors = validate(doc, "SessionDetailOut[]", [{ id: 1 }]);
    assert.ok(errors.includes("$[0].id: expected string, got number"), "a wrong type deep in a list");
    assert.ok(errors.some((e) => e.startsWith("$[0].title: required")), "and the missing fields");
    assert.ok(validate(doc, "FindingOut", { id: "f", kind: "nope" }).some((e) => e.startsWith("$.kind: \"nope\" is not one of")),
        "an enum value outside the contract");
});

QUnit.test("a keyword the validator does not implement throws instead of passing", function (assert) {
    const doc = (defs: Record<string, Record<string, unknown>>): SchemaDoc => ({ $defs: defs });
    assert.throws(() => validate(doc({ A: { allOf: [{ type: "string" }] } }), "A", "x"), /unsupported keyword allOf at \$/);
    assert.throws(() => validate(doc({ A: { type: "object", properties: { n: { type: "integer", maximum: 3 } } } }), "A", { n: 9 }),
        /unsupported keyword maximum at \$\.n/);
    assert.throws(() => validate(doc({ A: { type: "array", items: [{ type: "string" }] } }), "A", ["x"]),
        /unsupported keyword items \(tuple form\) at \$/);
    assert.throws(() => assertSupported(doc({ A: { type: "object", properties: { at: { type: "string", format: "date-time" } } } })),
        /unsupported keyword format at #\/\$defs\/A\/properties\/at/);
    assert.throws(() => assertSupported(doc({ A: { anyOf: [{ type: "array", minItems: 1 }] } })),
        /unsupported keyword minItems at #\/\$defs\/A\/anyOf\/0/);
    assert.deepEqual(validate(doc({ A: { title: "A", description: "d", default: 1, examples: [1], type: "integer" } }), "A", 1), [],
        "annotations pass");
});
